# - name: Download and unpack directly from HTTP source
#   unarchive:
#     src: "http://packages.confluent.io/archive/3.1/confluent-3.1.1-2.11.zip"
#     dest: "/home/ubuntu"
#     copy: no

- name: copy tls script
  copy:
    src: kafka-generate-ssl.sh
    dest: ~/kafka-generate-ssl.sh

# These files were created iniially manually with the certs-make-ap.sh script - you may need to run this yourself until it's automated
- name: upload tls / ssl keys
  copy:
    src: "{{ item }}"
    dest: ~/
  with_items:
    - kafka.server.keystore.jks
    - kafka.client.truststore.jks
    - kafka.server.truststore.jks

- name: Gets tarball
  get_url:
    url="http://packages.confluent.io/archive/3.3/confluent-3.3.1-2.11.tar.gz"
    dest="/home/ubuntu/confluent-3.3.1-2.11.tar.gz"
  register: new_archive

- name: Creates directory
  file: path=/home/ubuntu/cp state=directory

- name: Unarchive source
  #sudo: yes
  unarchive:
    src="/home/ubuntu/confluent-3.3.1-2.11.tar.gz"
    dest="/home/ubuntu/cp"
    copy=no

# link log dir and etc dir
- file:
    src: /home/ubuntu/cp/confluent-3.3.1/etc/kafka
    dest: /home/ubuntu/etc
    state: link

- file:
    src: /home/ubuntu/cp/confluent-3.3.1/logs
    dest: /home/ubuntu/logs
    state: link
    force: yes

# - name: Install java
#   sudo: yes
#   apt:
#     pkg: "{{ item }}"
#     state: present
#   with_items:
#     - default-jre # should use specific version
#     # - openjdk-8-jre-headless

- name: tools debug
  blockinfile:
    dest: cp/confluent-3.3.1/etc/kafka/tools-log4j.properties
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    # insertafter: "<body>"
    content: |
        log4j.rootLogger=DEBUG, stderr