# - name: Download and unpack directly from HTTP source
#   unarchive:
#     src: "http://packages.confluent.io/archive/3.1/confluent-3.1.1-2.11.zip"
#     dest: "/home/ubuntu"
#     copy: no

- name: Gets tarball
  get_url:
    url="http://packages.confluent.io/archive/3.1/confluent-3.1.1-2.11.tar.gz"
    dest="/home/ubuntu/"
  register: new_archive

- name: Creates directory
  file: path=/home/ubuntu/cp state=directory

- name: Unarchive source
  sudo: yes
  unarchive:
    src="/home/ubuntu/confluent-3.1.1-2.11.tar.gz"
    dest="/home/ubuntu/cp"
    copy=no

- name: Install java
  sudo: yes
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - openjdk-8-jre-headless
