---
- name: Ansible Control Server Ansible Setup
  hosts: role=bastion

  tasks:
    # install ansible 2.4, base has 2.0
    - name: Install base software?
      become: yes
      apt: name=software-properties-common state=latest
    - name: Add Ansible repo
      become: yes
      apt_repository: repo='ppa:ansible/ansible' state=present update_cache=yes
    - name: Install Ansible
      become: yes
      apt: name=ansible state=latest
