- name: Ansible Control Server deploy
  hosts: role=bastion

  tasks:
    - synchronize:
        src: ./
        dest: /home/ubuntu/ansible-playbooks-rsync 
        set_remote_user: yes
        delete: yes
        rsync_opts:
          - "--no-motd"
          - "--exclude=.git"
