---
# This playbook can actually be run on the ansible control server, after the code has
# been deployed. Actually much faster.
- name: Ansible Control Server Base setup
  hosts: role=bastion
  roles:
    -  role: common