---
- name: Ansible Control Server Ansible Setup
  hosts: role=bastion

  post_tasks:
    # install ansible 2.4, base has 2.0
    - sudo: yes
      apt: name=software-properties-common state=latest
    - sudo: yes
      apt_repository: repo='ppa:ansible/ansible' state=present update_cache=yes
    - sudo: yes
      apt: name=ansible state=latest
