# - name: Generate self signed certs
#   hosts: as-bastion-0-eu-west-1a
#   tasks:
#   - name: Generate a Self Signed OpenSSL certificate
#     openssl_certificate:
#       path: /etc/ssl/crt/ansible.com.crt
#       privatekey_path: /etc/ssl/private/ansible.com.pem
#       csr_path: /etc/ssl/csr/ansible.com.csr
#       provider: selfsigned

- hosts: as-bastion-0-eu-west-1a
  roles:
    - role: jdauphant.ssl-certs
      ssl_certs_common_name: "example.com"

# works
# - hosts: as-bastion-0-eu-west-1a
#   roles:
#     - jdauphant.ssl-certs
#     
  tasks:
  - name: Import SSL certificate from google.com to a given cacerts keystore
    become: yes
    java_cert:
      cert_path: /etc/ssl/example.com/example.com.pem
      cert_port: 443
      cert_alias: localhost
      keystore_create: yes
      keystore_path: /home/ubuntu/kafka.server.truststore.jks
      keystore_pass: changeit
      state: present