- hosts: [broker-cluster-1]
  roles:
     - kafka

- name: Deploy common role
  hosts: [c3]
  roles:
     - c3

- name: Deploy common role
  hosts: [zk-1]
  roles:
     - zk

- name: Deploy common role
  hosts: [connect-cluster-1]
  roles:
     - connect

# london follower
- hosts: [london-follower-cluster]
  roles:
     - kafka-london

- name: Deploy common role
  hosts: [london-zk]
  roles:
     - zk-london

