- name: Deploy common role
  hosts: [aws_tag_role=connect]
  tasks:

  - name: run connect
    command: >
      env 
      KAFKA_HEAP_OPTS="-Xms512m -Xmx2g"
      KAFKA_OPTS="-Djava.security.auth.login.config=kafka_connect_jaas.conf -Dlog4j.debug"
      cp/confluent-3.3.1/bin/connect-distributed -daemon cp/confluent-3.3.1/etc/kafka/connect-distributed.properties
  #cp/confluent-3.3.1/bin/connect-distributed cp/confluent-3.3.1/etc/kafka/connect-distributed.properties

  - name: wait for port
    wait_for: port=8083 delay=10
