- name: Deploy common role
  hosts: [aws_tag_role=connect]
  tasks:

  - name: killall java
    shell: killall java
    ignore_errors: yes

  - name: Wait for connect port to disaper # replace with process monitor
    wait_for:
      port: 8083
      state: absent
      timeout: 300
