- name: Deploy common role
  hosts: all
  roles:
     - hosts
  
  tasks:
  - name: download public hosts
    run_once: true
    fetch:
      src: public-hosts
      dest: public-hosts
      flat: yes

  - name: Reading host file as input for etc/hosts
    delegate_to: localhost
    run_once: true
    shell: cat public-hosts
    register: hosts

  - name: Copy public hosts into /etc/hosts
    become: yes
    run_once: yes
    delegate_to: localhost
    blockinfile:
      destfile: /etc/hosts
      marker: "<!-- {mark} Ansible Inventory -->"
      block: |
        {{ hosts.stdout }}
