- name: Stop kafka
  hosts: [aws_tag_role=broker]
  tasks:
  - name: run broker
    command: >
      env KAFKA_OPTS="
      -Djava.security.auth.login.config=kafka_server_jaas.conf
      -Dsun.security.krb5.debug=true
      -Dlog4j.debug
      -Djavax.net.debug=all"
      cp/confluent-3.3.1/bin/kafka-server-start -daemon 
      cp/confluent-3.3.1/etc/kafka/server.properties
