- name: performance producer start
  hosts: aws_tag_role=performance-producer

  vars:
    bootstrap: as-broker-0-{{ tags["region"] }}a:9092

  tasks:
  
    - name: killall java
      shell: killall java
      ignore_errors: yes
      become: true