- name: performance producer
  hosts: aws_tag_role=performance-producer
  roles:
     - client
  tasks:
    - name: killall java
      shell: killall java
      ignore_errors: yes
    - name: run perfromance client
      ignore_errors: no
      shell: > # the scalar doesn't seem to work, the line breaks are carried in
        CLASSPATH=cp/confluent-3.3.1/share/java/monitoring-interceptors/monitoring-interceptors-3.3.1.jar
        cp/confluent-3.3.1/bin/kafka-producer-perf-test
        --topic perf-10 
        --num-records 300000000 
        --record-size 1500 
        --throughput 10000
        --producer-props 
        client.id={{ inventory_hostname }}-{{ item }} 
        bootstrap.servers=as-broker-0-{{ tags["region"] }}a:9092 
        interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor 
        linger.ms=200 
        acks=all 
        compression.type=snappy 
        max.in.flight.requests.per.connection=2 
        > producer-{{ item }}.out 
        &
      with_items:
        - 1
        - 2
        - 3
