- name: performance producer start
  hosts: aws_tag_role=performance-producer

  vars:
    bootstrap: as-broker-0-{{ tags["region"] }}a:9092

  tasks:
  
    - name: killall java
      shell: killall java
      ignore_errors: yes
      become: true

    - name: run a single slow producer
      # async: 45
      # poll: 0
      shell: >
        CLASSPATH=cp/confluent-3.3.1/share/java/monitoring-interceptors/monitoring-interceptors-3.3.1.jar
        nohup
        cp/confluent-3.3.1/bin/kafka-producer-perf-test
        --topic r.slow-producer
        --num-records 10000000000
        --record-size 1500
        --throughput 100
        --producer-props 
        client.id={{ inventory_hostname }}-slow
        bootstrap.servers={{bootstrap}}
        interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor 
        linger.ms=0
        acks=all
        compression.type=snappy
        max.in.flight.requests.per.connection=2
        > producer-slow.out
        &

    - name: run perfromance client
      # async: 45
      # poll: 0
      shell: >
        CLASSPATH=cp/confluent-3.3.1/share/java/monitoring-interceptors/monitoring-interceptors-3.3.1.jar
        nohup
        cp/confluent-3.3.1/bin/kafka-producer-perf-test
        --topic r.perf-10 
        --num-records 10000000000
        --record-size 1500
        --throughput -1
        --producer-props 
        client.id={{ inventory_hostname }}-{{ item }} 
        bootstrap.servers={{bootstrap}}
        interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor 
        linger.ms=200
        acks=all
        compression.type=snappy
        max.in.flight.requests.per.connection=2
        > producer-{{ item }}.out
        &
      with_items:
        - 1
        - 2
        - 3
        - 4
        - 5
        # - 6
        # - 7
        # - 8
        # - 9
        # - 0
        # - 11
        # - 12
        # - 13
        # - 14
        # - 15
        # - 16
        # - 17
        # - 18
        # - 19
        # - 20

    # Have a single consumer consuming the whole topic for debug and for c3 to monitor
    # KAFKA_OPTS="-Djava.security.auth.login.config=kafka_client_jaas.pref -Dlog4j.debug"
    - name: run single consumer
      run_once: true
      shell: >
        CLASSPATH=cp/confluent-3.3.1/share/java/monitoring-interceptors/monitoring-interceptors-3.3.1.jar
        KAFKA_OPTS="-Dlog4j.debug"
        cp/confluent-3.3.1/bin/kafka-console-consumer
        --topic r.perf-10
        --new-consumer
        --bootstrap-server {{bootstrap}}
        --consumer-property interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor
        --consumer-property group.id=perf-topic-consumer-for-interceptors
        --consumer-property client.id=ptcfi-{{ inventory_hostname }}
        --consumer-property fetch.max.wait.ms=2
        > /dev/null
        &
