- name: performance producer
  hosts: aws_tag_role=performance-producer
  roles:
     - client
  vars:
    bootstrap: as-broker-0-{{ tags["region"] }}a:9092

- import_playbook: performance-producers-start.yml