- name: performance producer
  hosts: [aws_tag_role=performance-producer]
  roles:
     - client
  tasks:
    - name: run client
      command: >
        cp/confluent-3.3.1/bin/kafka-producer-perf-test 
        --topic perf-10
        --num-records 300000000 
        --record-size 1500
        --throughput 10000000 
        --producer-props bootstrap.servers=as-broker-0-{{ tags["region"] }}a:9092
          interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
          linger.ms=200 
          acks=all 
          compression.type=snappy 
          max.in.flight.requests.per.connection=2

# - name: stop client
#   command: cp/confluent-3.3.1/bin/...

