- name: performance producer
  hosts: aws_tag_role=performance-producer
  roles:
     - client
  tasks:
    # Make sure permissions are correct. Was used to correct a sudo mistale.
    # - name: Ensure directories are 0755
    #   become: true
    #   command: chown ubuntu -R /home/ubuntu
    - name: killall java
      shell: killall java
      ignore_errors: yes
      become: true
    - name: run perfromance client
      # async: 45
      # poll: 0
      shell: >
        CLASSPATH=cp/confluent-3.3.1/share/java/monitoring-interceptors/monitoring-interceptors-3.3.1.jar
        nohup
        cp/confluent-3.3.1/bin/kafka-producer-perf-test
        --topic r.perf-10 
        --num-records 300000000 
        --record-size 1500 
        --throughput -1
        --producer-props 
        client.id={{ inventory_hostname }}-{{ item }} 
        bootstrap.servers=as-broker-0-{{ tags["region"] }}a:9092 
        interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor 
        linger.ms=200 
        acks=all 
        compression.type=snappy 
        max.in.flight.requests.per.connection=2 
        > producer-{{ item }}.out 
        &
      with_items:
        - 1
        - 2
        - 3
        - 4
        - 5
        - 6
        - 7
        - 8
        - 9
        - 0
