- name: Setup for proof producer
  hosts: [aws_tag_role=performance-producer, aws_tag_role=performance-consumer]
  strategy: free
  tasks:

    - synchronize:
        src: /Users/antony/repos/practice/gradle-practice
        dest: /home/ubuntu/stubbs-kafka-streams-examples
        set_remote_user: yes
        delete: yes
        rsync_opts:
          - "--no-motd"
          - "--exclude=.git"
          - "--exclude=build"
          - "--exclude=out"

    - name: "Compile"
      shell: >
        cd stubbs-kafka-streams-examples/gradle-practice;
        gradle fatjar
