- name: Proof producer
  hosts: aws_tag_role=performance-producer
  vars:
    jarLocation: ~/stubbs-kafka-streams-examples/gradle-practice/

  tasks:
    - name: killall java
      shell: killall java
      ignore_errors: yes
      become: true

    - name: run perfromance client
      shell: >
        cd {{ jarLocation }};
        java -Dlog4j.debug -cp build/libs/confluent-training-1.0-SNAPSHOT.jar stubbs.ProofProducer 
        --broker as-broker-0-eu-west-1a 
        --count 10000
        --topic r.aws-proof-1 
        --id 4 
        --size 1500
        2>&1 > producer-{{ item }}.out 
        &
      with_items:
        - 1
