- name: Setup for proof producer
  hosts: [aws_tag_role=performance-producer, aws_tag_role=performance-consumer]
  roles:
     - client
  strategy: free
  tasks:
    # - name: "Clone stubbs examples"
    #   git: 
    #     repo: git@github.org:"astubbs/stubbs-kafka-streams-examples.git"
    #     dest: "~/stubbs-kafka-streams-examples.git"
    #     accept_hostkey: True
    #     # refspec=master
    #     # version=docker

    - name: killall java - brutally - in case performance producers are still running
      shell: killall java
      ignore_errors: yes
      become: true

    - name: Install base packages
      become: true
      apt:
        pkg: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - gradle 
        - openjdk-8-jdk-headless
