- name: Proof analyser
  hosts: aws_tag_role=performance-consumer
  vars:
    jarLocation: ~/stubbs-kafka-streams-examples/gradle-practice/

  tasks:
    - name: killall java
      shell: killall java
      ignore_errors: yes
      become: true

    - name: run perfromance client
      shell: >
        cd {{ jarLocation }};
        java -Dlog4j.debug -cp build/libs/confluent-training-1.0-SNAPSHOT.jar stubbs.ProofAnalyser 
        --topic r.aws-proof-1 
        --broker as-broker-0-eu-central-1a 
        --count 10000
        --id 4 
        --threads 4
        2>&1 > analyser-{{ item }}.out 
        &
      with_items:
        - 1
