---
- hosts: connect_va
  tasks:
  - name: DELETE Replicator config
    run_once: yes
    uri:
      url: http://localhost:8083/connectors/performance-replication-ca-va
      method: DELETE
      status_code: 204
