- import_playbook: python-fix.yml

- import_playbook: common.yml

- import_playbook: cp-install.yml

- import_playbook: zk-setup.yml

- import_playbook: kafka.yml

- import_playbook: c3.yml

- import_playbook: connect.yml

- import_playbook: topic-setup.yml

- import_playbook: performance-producers.yml

- import_playbook: performance-consumers.yml

# - import_playbook: streams.yml