- name: Entire fleet
  hosts: all
  strategy: free

- import_playbook: python-fix.yml

- import_playbook: hosts.yml

- import_playbook: common.yml

- import_playbook: cp-install.yml

# skip server software - just do the clients

- import_playbook: performance-producers.yml

- import_playbook: performance-consumers.yml

