- import_playbook: python-fix.yml

- name: Software
  hosts: all
  strategy: free

- import_playbook: zk-setup.yml

- import_playbook: kafka.yml

- import_playbook: c3.yml

- import_playbook: connect.yml

- import_playbook: topic-setup.yml

- import_playbook: performance-producers.yml

- import_playbook: performance-consumers.yml

# - import_playbook: proof-setup.yml

# - import_playbook: proof-redeploy.yml
