- import_playbook: python-fix.yml

- name: Base setup
  hosts: all
  strategy: free
  any_errors_fatal: true

- import_playbook: hosts.yml

- import_playbook: common.yml

- import_playbook: cp-install.yml

- import_playbook: docker.yml
