- name: setup topics
  hosts: as-broker-0-eu-west-1a
  tasks:
    - name: performance topc
      shell: >
        cp/confluent-3.3.1/bin/kafka-topics 
        --create 
        --zookeeper as-zookeeper-0-eu-west-1a:2181 
        --topic r.perf-10 
        --partitions 10 
        --replication-factor 3 > 1.done
      ignore_errors: yes
      args:
        creates: 1.done

    - name: correctness topic
      shell: >
        cp/confluent-3.3.1/bin/kafka-topics 
        --create 
        --zookeeper 
        as-zookeeper-0-eu-west-1a:2181 
        --topic r.correctness-10 
        --partitions 10 
        --replication-factor 3 > 2.done
      ignore_errors: yes
      args:
        creates: 2.done
