- name: Deploy common role
  hosts: role=zookeeper
  strategy: free
  tasks:

  - name: killall java
    shell: killall java
    ignore_errors: yes
    become: yes

  - name: run zk
    command: >
      env KAFKA_OPTS="-Djava.security.auth.login.config=zookeeper_jaas.conf" 
      cp/confluent-3.3.1/bin/zookeeper-server-start -daemon cp/confluent-3.3.1/etc/kafka/zookeeper.properties
