- blockinfile:
    destfile: /home/ubuntu/cp/confluent-3.1.1/etc/confluent-control-center/control-center.properties
    block: |
      zookeeper.connect=zk1.tony:2181,zk2.tony:2181,zk3.tony:2181
      bootstrap.servers=bk1.tony:9092,bk2.tony:9092,bk3.tony:9092
      confluent.controlcenter.connect.cluster=cc1.tony:8083,cc2.tony:8083
      confluent.controlcenter.internal.topics.replication=3
      confluent.monitoring.interceptor.topic.replication=3
      confluent.controlcenter.command.topic.replication=3

- name: run c3
  command: cp/confluent-3.1.1/bin/control-center-start -daemon  cp/confluent-3.1.1/etc/confluent-control-center/control-center.properties
