- blockinfile:
    destfile: /home/ubuntu/cp/confluent-3.3.1/etc/confluent-control-center/control-center.properties
    block: |
      zookeeper.connect=as-zookeeper-0-{{ tags["region"] }}a:2181
      bootstrap.servers=as-broker-0-{{ tags["region"] }}a:9092
      confluent.controlcenter.connect.cluster=as-connect-0-{{ tags["region"] }}a:8083
      confluent.controlcenter.internal.topics.replication=3
      confluent.monitoring.interceptor.topic.replication=3
      confluent.controlcenter.command.topic.replication=3

- name: run c3
  command: cp/confluent-3.3.1/bin/control-center-start -daemon cp/confluent-3.3.1/etc/confluent-control-center/control-center.properties > /tmp/c3.out