- blockinfile:
    destfile: /home/ubuntu/cp/confluent-3.3.1/etc/kafka/zookeeper.properties
    block: |
      initLimit=5
      syncLimit=2
      server.0=as-zookeeper-0-{{ tags["region"] }}a:2888:3888
      server.1=as-zookeeper-1-{{ tags["region"] }}b:2888:3888
      server.2=as-zookeeper-2-{{ tags["region"] }}c:2888:3888

- lineinfile:
    destfile: /tmp/zookeeper/myid
    create: yes
    line: '{{tags["zookeeperid"]}}'

# - replace:
#     destfile: /home/ubuntu/cp/confluent-3.1.1/etc/kafka/zookeeper.properties
#     regexp: 'maxClientCnxns=0'
#     replace: 'maxClientCnxns=0\n\n\ninitLimit=5\nsyncLimit=2\nserver.1=ip-172-31-28-232.eu-west-1.compute.internal:2888:3888\nserver.2=ip-172-31-34-197.eu-west-1.compute.internal:2888:3888\nserver.3=ip-172-31-5-13.eu-west-1.compute.internal:2888:3888\n'
#     backup: yes

- name: killall java
  shell: killall java
  ignore_errors: yes
  become: yes

- name: run zk
  command: cp/confluent-3.3.1/bin/zookeeper-server-start -daemon cp/confluent-3.3.1/etc/kafka/zookeeper.properties