- name: killall java
  shell: killall java
  ignore_errors: yes
  become: yes

- name: Wait for port to disappear # replace with process monitor
  wait_for:
    port: "2181"
    state: absent
    timeout: 300

- name: base settings
  blockinfile:
    destfile: /home/ubuntu/cp/confluent-3.3.1/etc/kafka/zookeeper.properties
    marker: "<!-- {mark} CLUSTER CONFIG -->"
    block: |
      initLimit=5
      syncLimit=2
      server.0=as-zookeeper-0-{{ tags["region"] }}a:2888:3888
      server.1=as-zookeeper-1-{{ tags["region"] }}b:2888:3888
      server.2=as-zookeeper-2-{{ tags["region"] }}c:2888:3888

- name: zk id file
  lineinfile:
    destfile: /tmp/zookeeper/myid
    create: yes
    line: '{{tags["zookeeperid"]}}'

- name: security block
  blockinfile:
    destfile: /home/ubuntu/cp/confluent-3.3.1/etc/kafka/zookeeper.properties
    marker: "<!-- {mark} SECURITY CONFIG -->"
    block: |
      # security settings
      authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider
      requireClientAuthScheme=sasl
      jaasLoginRenew=3600000

# - replace:
#     destfile: /home/ubuntu/cp/confluent-3.1.1/etc/kafka/zookeeper.properties
#     regexp: 'maxClientCnxns=0'
#     replace: 'maxClientCnxns=0\n\n\ninitLimit=5\nsyncLimit=2\nserver.1=ip-172-31-28-232.eu-west-1.compute.internal:2888:3888\nserver.2=ip-172-31-34-197.eu-west-1.compute.internal:2888:3888\nserver.3=ip-172-31-5-13.eu-west-1.compute.internal:2888:3888\n'
#     backup: yes

- name: create security dir
  file:
      path: /etc/security/keytabs
      state: directory
  become: yes
  # ignore_errors: yes

- name: copy keytabs
  copy: 
    src: "{{ role_path }}/../../secrets/{{item}}"
    dest: /etc/security/keytabs/
  with_items: 
    - zookeeper-{{ tags["region"] }}.keytab
  become: yes

- name: upload JAAS file
  template:
    src: zookeeper_jaas.conf.j2
    dest: ~/zookeeper_jaas.conf

# Simply passing the JAAS config doesn't mean it's required
- name: run zk
  command: >
    env KAFKA_OPTS="-Djava.security.auth.login.config=zookeeper_jaas.conf -Dlog4j.debug -Djavax.net.debug=all -Dsun.security.krb5.debug=true"
    cp/confluent-3.3.1/bin/zookeeper-server-start -daemon cp/confluent-3.3.1/etc/kafka/zookeeper.properties





