- replace:
    destfile: /home/ubuntu/cp/confluent-3.1.1/etc/kafka/server.properties
    regexp: 'broker.id=0'
    replace: 'broker.id={{b_id}}'
    backup: yes

- replace:
    destfile: /home/ubuntu/cp/confluent-3.1.1/etc/kafka/server.properties
    regexp: 'num.partitions=1'
    replace: 'num.partitions=3'
    backup: yes

- replace:
    destfile: /home/ubuntu/cp/confluent-3.1.1/etc/kafka/server.properties
    regexp: 'zookeeper.connect=localhost:2181'
    replace: 'zookeeper.connect=172.31.14.70'
    backup: yes


- command: cp/confluent-3.1.1/bin/kafka-server-start -daemon cp/confluent-3.1.1/etc/kafka/server.properties

  