# use a single sed instead
- replace:
    destfile: /home/ubuntu/cp/confluent-3.3.1/etc/kafka/server.properties
    regexp: 'broker.id=0'
    replace: 'broker.id={{tags["brokerid"]}}'
    backup: yes

- replace:
    destfile: /home/ubuntu/cp/confluent-3.3.1/etc/kafka/server.properties
    regexp: 'num.partitions=1'
    replace: 'num.partitions=3'
    backup: yes

- replace:
    destfile: /home/ubuntu/cp/confluent-3.3.1/etc/kafka/server.properties
    regexp: 'zookeeper.connect=.*'
    replace: 'zookeeper.connect=as-zookeeper-0-{{ tags["region"] }}a'
    backup: yes

- name: insert/update HTML surrounded by custom markers after <body> line
  blockinfile:
    path: /home/ubuntu/cp/confluent-3.3.1/etc/kafka/server.properties
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    # insertafter: "<body>"
    content: |
        offsets.topic.replication.factor=3
        transaction.state.log.replication.factor=3
        transaction.state.log.min.isr=2
        metric.reporters=io.confluent.metrics.reporter.ConfluentMetricsReporter
        confluent.metrics.reporter.bootstrap.servers=localhost:9092
        confluent.metrics.reporter.zookeeper.connect=localhost:2181
        confluent.metrics.reporter.topic.replicas=3
        delete.topic.enable=true
        num.partitions=3

- name: stop boker
  command: cp/confluent-3.3.1/bin/kafka-server-stop

- name: run boker
  command: cp/confluent-3.3.1/bin/kafka-server-start -daemon cp/confluent-3.3.1/etc/kafka/server.properties
