# use a single sed instead
- replace:
    destfile: /home/ubuntu/cp/confluent-3.3.1/etc/kafka/server.properties
    regexp: 'broker.id=0'
    replace: 'broker.id={{tags["brokerid"]}}'
    backup: yes

- replace:
    destfile: /home/ubuntu/cp/confluent-3.3.1/etc/kafka/server.properties
    regexp: 'num.partitions=1'
    replace: 'num.partitions=3'
    backup: yes

# use host names for zk
- replace:
    destfile: /home/ubuntu/cp/confluent-3.3.1/etc/kafka/server.properties
    regexp: 'zookeeper.connect=localhost:2181'
    replace: 'zookeeper.connect=ip-172-31-25-178.eu-west-1.compute.internal'
    backup: yes

- name: run boker
  command: cp/confluent-3.3.1/bin/kafka-server-start -daemon cp/confluent-3.3.1/etc/kafka/server.properties
