# use a single sed instead
- replace:
    destfile: /home/ubuntu/cp/confluent-3.3.1/etc/kafka/server.properties
    regexp: 'broker.id=0'
    replace: 'broker.id={{tags["brokerid"]}}'
    backup: yes

- replace:
    destfile: /home/ubuntu/cp/confluent-3.3.1/etc/kafka/server.properties
    regexp: 'num.partitions=1'
    replace: 'num.partitions=3'
    backup: yes

- name: zk bootstrap
  vars:
    zkhostname: as-zookeeper-0-{{ tags.region }}a
  replace:
    destfile: /home/ubuntu/cp/confluent-3.3.1/etc/kafka/server.properties
    regexp: 'zookeeper.connect=.*'
    replace: zookeeper.connect={{ hostvars[zkhostname].public.dns }}
    backup: yes

- name: insert/update text surrounded by custom markers
  blockinfile:
    path: /home/ubuntu/cp/confluent-3.3.1/etc/kafka/server.properties
    marker: "<!-- {mark} ANSIBLE MANAGED BLOCK -->"
    # insertafter: "<body>"
    content: |
        default.replication.factor=3
        offsets.topic.replication.factor=3
        transaction.state.log.replication.factor=3
        transaction.state.log.min.isr=2
        metric.reporters=io.confluent.metrics.reporter.ConfluentMetricsReporter
        confluent.metrics.reporter.bootstrap.servers=localhost:9092
        confluent.metrics.reporter.zookeeper.connect=localhost:2181
        confluent.metrics.reporter.topic.replicas=3
        delete.topic.enable=true
        # over partition
        num.partitions=20
        # 20GB in B
        log.retention.bytes=20000000000
        # default 60000
        # log.segment.delete.delay.ms=30000
        # default 300000
        # log.retention.check.interval.ms=30000
        listeners=PLAINTEXT://:9092
        advertised.listeners=PLAINTEXT://{{ public['dns'] }}:9092


- name: run boker
  command: cp/confluent-3.3.1/bin/kafka-server-start -daemon cp/confluent-3.3.1/etc/kafka/server.properties
# cp/confluent-3.3.1/bin/kafka-server-start cp/confluent-3.3.1/etc/kafka/server.properties
