- replace:
    destfile: /home/ubuntu/cp/confluent-3.1.1/etc/kafka/server.properties
    regexp: 'broker.id=0'
    replace: 'broker.id={{b_id}}'
    backup: yes

- replace:
    destfile: /home/ubuntu/cp/confluent-3.1.1/etc/kafka/server.properties
    regexp: 'num.partitions=1'
    replace: 'num.partitions=3'
    backup: yes

- replace:
    destfile: /home/ubuntu/cp/confluent-3.1.1/etc/kafka/server.properties
    regexp: 'zookeeper.connect=localhost:2181'
    replace: 'zookeeper.connect=ip-172-31-28-232.eu-west-1.compute.internal,ip-172-31-34-197.eu-west-1.compute.internal,ip-172-31-5-13.eu-west-1.compute.internal'
    backup: yes


- name: run boker
  command: cp/confluent-3.1.1/bin/kafka-server-start -daemon cp/confluent-3.1.1/etc/kafka/server.properties

  
