---
kafka:
  ports:
    plain: 9092
    sasl_ssl: 9093
    sasl_plaintext: 9094
    ssl: 9095
  ssl_truststore_location: /home/ubuntu/kafka.client.truststore.jks
  ssl_keystore_location: /home/ubuntu/kafka.server.keystore.jks
  store_password: password123
cp_version: 3.3.1 ## can't use embedded vars?!
cp:
  version: "{{ cp_version }}"
  path: "/home/ubuntu/cp/confluent-{{ cp_version }}"

kafka_port: "{{kafka.ports.plain}}"
connect_port: 8083
# kafka_security_protocol: SASL_PLAINTEXT
