# Broker Users
broker_user_actual:
  login: broker
  secret: broker-secret
broker_users:
- login: perf
  secret: perf-secret
- login: proof
  secret: proof-secret
- login: readonly
  secret: readonly-secret
- login: singlereader
  secret: singlereader-secret
- login: admin
  secret: admin-secret
- login: connect
  secret: connect-secret
- login: c3
  secret: c3-secret
- login: broker
  secret: broker-secret
zk_broker:
  login: broker
  secret: broker-secret
kafka_paths:
  properties: "{{cp.path}}/etc/kafka/server.properties"