# - name: update host file
#   lineinfile:
#     dest: /etc/hosts
#     regexp: '{{ hostvars[item].private_ipv4 }}.*{{ item }}$'
#     line: "{{ hostvars[item].private_ipv4 }} {{item}}"
#     state: present
#   become: yes
#   with_items: "{{ groups.all }}"

# Base packages, utilities and docker
- name: Install base packages
  environment: 
   DEBIAN_FRONTEND: noninteractive
  become: true
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    #- python-pip
    - fish
    #- git
    - ncdu # handy space utilisation util
    - ntop # better top
    - iotop
    - lynx # text only web browser, super useful
    - vim # need I say more
    - python-minimal
    #- s3cmd # interacting with s3 buckets
    #- postgresql-client # interacting with postgres databases - NB: isn't server software
    #- golang # for ccat, go experiments and other go util programs
    - htop # better top
    - unzip
    - zookeeper # zookeeper client zkCli
    - jq # clu json parser
    - iftop # network connection monitoring
    #- openjdk-8-jre-headless
    - default-jre
    - python-openssl
    - krb5-user

- name: Set shell to fish
  user: name=ubuntu shell=/usr/bin/fish #breaks unarchive
  #user: name=ubuntu shell=/bin/bash
  become: yes

- name: set nice hostname
  hostname:
    name: "{{inventory_hostname}}"
  become: yes

# this should be dynamic but is hard coded for poc
- name: configure krb5.conf default realm
  replace:
    destfile: /etc/krb5.conf
    regexp: 'default_realm = (.*)$'
    replace: 'default_realm = {{ tags["region"] | upper}}.CONFLUENT.IO'
  become: yes

- name: configure krb5.conf realm
  blockinfile:
    destfile: /etc/krb5.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK CENTRAL REALM"
    insertafter: '\[realms\]'
    block: |
     EU-CENTRAL-1.CONFLUENT.IO = {
        kdc = as-c3-0-eu-central-1a:88
        admin_server = as-c3-0-eu-central-1a:750
        default_domain = eu-central-1.confluent.io
      }
  become: yes

# this should be dynamic but is hard coded for poc
- name: configure krb5.conf alternate realm
  blockinfile:
    destfile: /etc/krb5.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK WEST REALM"
    insertafter: '\[realms\]'
    block: |
     EU-WEST-1.CONFLUENT.IO = {
        kdc = as-c3-0-eu-west-1a:88
        admin_server = as-c3-0-eu-west-1a:750
        default_domain = eu-west-1.confluent.io
      }
  become: yes

- name: configure krb5.conf domain
  blockinfile:
    destfile: /etc/krb5.conf
    marker: "# {mark} ANSIBLE MANAGED BLOCK DOMAIN"
    insertafter: '\[domain_realm\]'
    block: |
      .eu-west-1.confluent.io = EU-WEST-1.CONFLUENT.IO
      eu-west-1.confluent.io = EU-WEST-1.CONFLUENT.IO
      .eu-central-1.confluent.io = EU-CENTRAL-1.CONFLUENT.IO
      eu-central-1.confluent.io = EU-CENTRAL-1.CONFLUENT.IO
  become: yes
