# - name: update host file
#   lineinfile:
#     dest: /etc/hosts
#     regexp: '{{ hostvars[item].private_ipv4 }}.*{{ item }}$'
#     line: "{{ hostvars[item].private_ipv4 }} {{item}}"
#     state: present
#   become: yes
#   with_items: "{{ groups.all }}"

# Base packages, utilities and docker
- name: Install base packages
  become: true
  apt:
    pkg: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    #- python-pip
    - fish
    #- git
    - ncdu # handy space utilisation util
    - ntop # better top
    - iotop
    - lynx # text only web browser, super useful
    - vim # need I say more
    #- s3cmd # interacting with s3 buckets
    #- postgresql-client # interacting with postgres databases - NB: isn't server software
    #- golang # for ccat, go experiments and other go util programs
    - htop # better top
    - unzip
    - zookeeper # zookeeper client zkCli
    - jq # clu json parser
    - iftop # network connection monitoring
    #- openjdk-8-jre-headless
    - default-jre
    - python-openssl

- name: Set shell to fish
  user: name=ubuntu shell=/usr/bin/fish #breaks unarchive
  # user: name=ubuntu shell=/bin/bash
  become: yes

# - hostname:
#     name: "{{node_name}}"

# - command: hostname {{tags['big-nice-name']}} #{{node_name}}
  # sudo: yes
