# elastic seems to require this: https://github.com/spujadas/elk-docker/issues/92"
- name: set vm max map count
  become: true
  sysctl:
    name: vm.max_map_count
    value: 262144
    state: present

- name: Elasticsearch
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.5
    restart_policy: on-failure
    network_mode: host
    ports:
      - "9200:9200"
      - "9300:9300"
    env:
       xpack.security.enabled: "false"

- name: Kibana
  docker_container:
    name: kibana
    image: docker.elastic.co/kibana/kibana:5.6.5
    restart_policy: on-failure
    network_mode: host
    ports:
      - "5601:5601"
    env:
       xpack.security.enabled: "false"
       XPACK_SECURITY_ENABLED: "false"
       ELASTICSEARCH_URL: http://localhost:9200
    # depends_on:
    #   - elasticsearch

- name: kibana_index_pattern
  docker_container:
    name: kibana_index_pattern
    image: tutum/curl
    command: "bash -c \"sleep 30 ; curl 'http://localhost:5601/es_admin/.kibana/index-pattern/logstash-*/_create' -H 'kbn-version: 5.5.2' -H 'content-type: application/json' --data-binary '{\"title\":\"logstash-*\",\"timeFieldName\":\"@timestamp\",\"notExpandable\":true}'\""
