- name: add interceptor to class path
  lineinfile:
    path: /home/ubuntu/.bash_profile
    create: yes
    line: 'export CLASSPATH=$CLASSPATH:cp/confluent-3.3.1/share/java/monitoring-interceptors/monitoring-interceptors-3.3.1.jar'

# First env vars?
#- shell: set -gx CLASSPATH $CLASSPATH:cp/confluent-3.3.1/share/java/monitoring-interceptors/monitoring-interceptors-3.3.1.jar

- name: upload consumer properties file
  copy:
    src: consumer.properties
    dest: ./consumer.properties