- name: add interceptor to class path
  lineinfile:
    path: /home/ubuntu/.bash_profile
    create: yes
    line: 'export CLASSPATH=$CLASSPATH:cp/confluent-3.3.1/share/java/monitoring-interceptors/monitoring-interceptors-3.3.1.jar'

# First env vars?
#- shell: set -gx CLASSPATH $CLASSPATH:cp/confluent-3.3.1/share/java/monitoring-interceptors/monitoring-interceptors-3.3.1.jar

- name: upload consumer properties file
  template:
    src: consumer.properties.j2
    dest: ~/consumer.properties

- name: create security dir
  shell: mkdir /etc/security/keytabs
  ignore_errors: yes
  sudo: yes

- name: copy keytabs
  copy: 
    src: "{{ role_path }}/../../secrets/{{item}}"
    dest: /etc/security/keytabs/
  with_items: 
    - client-{{ tags["region"] }}.keytab
  sudo: yes


- name: upload consumer security file
  template:
    src: kafka_client_jaas.conf.j2
    dest: ~/kafka_client_jaas.conf

# bin/kafka-console-consumer --topic aws-proof-1 --new-consumer --bootstrap-server localhost:10092 --consumer-property security.protocol=SASL_PLAINTEXT --consumer-property sasl.mechanism=GSSAPI,PLAIN
