- name: Generate /etc/hosts file
  template:
    src=hosts.j2
    dest=/etc/hosts

- name: Generate public hosts file
  template:
    src=public-hosts.j2
    dest=./public-hosts

# - name: update host file
#   lineinfile:
#     dest: /etc/hosts
#     regexp: '{{ hostvars[item].private_ipv4 }}.*{{ item }}$'
#     line: "{{ hostvars[item].private_ipv4 }} {{item}}"
#     state: present
#   become: yes
#   with_items: "{{ groups.all }}"