- blockinfile:
    destfile: /home/ubuntu/cp/confluent-3.1.1/etc/kafka/connect-distributed.properties
    block: |
      bootstrap.servers=bk1.tony:9092,bk2.tony:9092,bk3.tony:9092
      producer.interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
      consumer.interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor


- name: run connect
  command: cp/confluent-3.1.1/bin/connect-distributed  -daemon cp/confluent-3.1.1/etc/kafka/connect-distributed.properties
