# producer.interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor
# consumer.interceptor.classes=io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor

- blockinfile:
    destfile: /home/ubuntu/cp/confluent-3.3.1/etc/kafka/connect-distributed.properties
    block: |
      bootstrap.servers=as-broker-0-{{ tags["region"] }}a:9092
      group.id=frankfurt-connect

- name: killall java
  shell: killall java
  ignore_errors: yes

- name: run connect
  command: cp/confluent-3.3.1/bin/connect-distributed -daemon cp/confluent-3.3.1/etc/kafka/connect-distributed.properties
